---
- name: Create systemd drop-in directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Set Proxy
  template:
    src: 10-proxy.conf.j2
    dest:
      /etc/systemd/system/docker.service.d/10-proxy.conf
  notify:
    - reload systemd
